@startuml Asunto
entity Persona {
  * IdPersona
  CI
  Nombre
  Celular
  Dirección
}

entity Cliente extends Persona {
}

entity Asunto{
  *Numero_expediente
  Fecha_inicio
  Fecha_fin
  Estado
}

entity Abogado extends Persona {
  Registro_de_Abogado
}	

Cliente ||--|{ Asunto
Abogado }o--|{ Asunto   

@enduml

