@startuml Asuntos_especializados
entity Persona {
  *IdPersona
  CI
  Nombre
  Celular
  Dirección
}

entity Cliente extends Persona {
}

entity Asunto{
  *Número_expediente
  Fecha_inicio
  Fecha_fin
  Estado
}

entity Abogado extends Persona {
  Registro_Abogado
}	

Cliente ||--|{ Asunto
Abogado }o--|{ Asunto   

@enduml

