@startuml Recetario

entity Receta{
  *idReceta
  Tiempo_ejecucion
  Fuente
  Ubicacion_fisica
}

entity Pasos_receta {
  *idReceta
  Operacion
  Tiempo
  Comentario
}
 
entity Ingrediente {
  *idIngrediente
  Nombre
  Calorias
  Unidad
}

entity Utensilio {
  *idUtensilio
  Nombre_utensilio
}

entity Menu {
  *Correlativo_menu
  Precio
  Comentario
}

entity Plato {
  *IdPlato
  Nombre
  Precio
  Comentario
  Tipo_plato
}

Receta *--|{ Pasos_receta
Receta |o--|{ Pasos_receta
Pasos_receta *--|{ Ingrediente :-[Cantidad]
Pasos_receta }o--|{ Utensilio
Plato ||--|{ Receta
Plato *--|| Ingrediente :-[Principal]
Plato }|--o Menu :-[Primero]
Plato }|--o Menu :-[Segundo]
Plato }|--o Menu :-[Postre]

@enduml