@startuml Zoo
entity Zoo {
  * idZoo
  Nombre
  Ciudad
  País
  Tamaño
  Presupuesto_anual
}

entity Especie {
  * idEspecie
  Nombre_vulgar
  Nombre_científico
  Familia
  Peligro_extinción
}

entity Animal {
  * idAnimal
  Sexo
  Año_nacimiento
  País_origen
  Continente
}
@enduml
